GET http://localhost:3000/api/cats

###

POST http://localhost:3000/api/cats
Content-Type: application/json

{
   "name": "Kitkat",
   "age": 5,
   "color": "White"
}

###

PUT http://localhost:3000/api/cats/61160fba-ec1f-4905-8e39-9ce9db2f362c
Content-Type: application/json

{
   "id": "61160fba-ec1f-4905-8e39-9ce9db2f362c",
   "name": "Scoob",
   "age": 3,
   "color": "Orange"
}

###

DELETE http://localhost:3000/api/cats/32cbd8aa-c888-4978-8107-1230b9d25848

