GET http://localhost:3000/api/cats

###

POST http://localhost:3000/api/cats
Content-Type: application/json

{
   "name": "Cocos",
   "age": 5,
   "color": "Red"
}

###

PUT http://localhost:3000/api/cats/16bbbd1f-30db-42bf-b083-525a2756c065
Content-Type: application/json

{
   "name": "Scoob",
   "age": 3,
   "color": "Gray"
}

###

DELETE http://localhost:3000/api/cats/16bbbd1f-30db-42

