GET http://localhost:3000/api/cats

###

POST http://localhost:3000/api/cats
Content-Type: application/json

{
   "name": "Twister",
   "age": 3,
   "color": "Gray"
}

###

PUT http://localhost:3000/api/cats/f3e675d4-9f76-4469-b36f-8ce31ab4b96a
Content-Type: application/json

{
   "name": "Twister",
   "age": 3,
   "color": "Gray"
}

###

DELETE http://localhost:3000/api/cats/f3e675d4-9f76-4469-b36f-8ce31ab4b96a

